{
  imports = [
    ./autopair.nix
    ./basic.nix
    ./comment.nix
    ./completion.nix
    ./core.nix
    ./filetree.nix
    ./git.nix
    ./lsp
    ./statusline.nix
    ./surround.nix
    ./telescope.nix
    ./theme.nix
    ./treesitter.nix
    ./ui.nix
    ./visuals.nix
  ];
}
